### ISSUE TITLE
按照示例启动后，看到dashboard

### ISSUE THREAD

**Issue by wadeDra** [midwayjs/sandbox-docker#6]
我操作有误吗？
1.clone
2.docker-compose build && sudo docker-compose up
3.访问7001或者9081均没有看到dashboard

如何才能看得到呢？在本地我想调试一下看看

**Comment by wadeDra** [comment]
sanbox-app中的config你的log配置成了logger……

**Comment by guangwong** [comment]
明天我再确认一下， 现在跑起来了么

**Comment by wadeDra** [comment]
嗯 跑起来了  你得改一下
